-- MySQL Script generated by MySQL Workbench
-- Fri Jul  3 20:14:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qa-scope
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qa-scope
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qa-scope` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `qa-scope` ;

-- -----------------------------------------------------
-- Table `qa-scope`.`1. Consultation_Master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qa-scope`.`1. Consultation_Master` (
  `consultation_id` INT NOT NULL,
  PRIMARY KEY (`consultation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qa-scope`.`2. Consultation_Dialogues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qa-scope`.`2. Consultation_Dialogues` (
  `dialogue_id` INT NOT NULL,
  PRIMARY KEY (`dialogue_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qa-scope`.`3-A. AI_Evaluation_Master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qa-scope`.`3-A. AI_Evaluation_Master` (
  `evaluation_id` INT NOT NULL,
  PRIMARY KEY (`evaluation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qa-scope`.`3-B. AI_Evaluation_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qa-scope`.`3-B. AI_Evaluation_Details` (
  `detail_id` INT NOT NULL,
  PRIMARY KEY (`detail_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qa-scope`.`3-C. AI_Evaluation_Risk_Flags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qa-scope`.`3-C. AI_Evaluation_Risk_Flags` (
  `flag_id` INT NOT NULL,
  PRIMARY KEY (`flag_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
